INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_VHFPULSEDETECT VHFPulseDetect)

FIND_PATH(
    VHFPULSEDETECT_INCLUDE_DIRS
    NAMES VHFPulseDetect/api.h
    HINTS $ENV{VHFPULSEDETECT_DIR}/include
        ${PC_VHFPULSEDETECT_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    VHFPULSEDETECT_LIBRARIES
    NAMES gnuradio-VHFPulseDetect
    HINTS $ENV{VHFPULSEDETECT_DIR}/lib
        ${PC_VHFPULSEDETECT_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(VHFPULSEDETECT DEFAULT_MSG VHFPULSEDETECT_LIBRARIES VHFPULSEDETECT_INCLUDE_DIRS)
MARK_AS_ADVANCED(VHFPULSEDETECT_LIBRARIES VHFPULSEDETECT_INCLUDE_DIRS)

